### ISSUE TITLE
not working on my super super mac

### ISSUE THREAD

**Issue by jerexyz** [gucong3000/mirror-config-china#5]
例如 [phantomjs](https://www.npmjs.com/package/phantomjs) 的环境变量

**Comment by gucong3000** [comment]
请尝试下面两条命令，并分别将运行结果贴上来
``bash`
 set | grep http
```

···bash
npm config list
···

**Comment by jerexyz** [comment]
` 15:16:54  ~/jm/shequ  ☿ 2455@dev ± 
$ set | grep http
Binary file (standard input) matches

 15:29:20  ~/jm/shequ  ☿ 2456@dev 
$ npm config list
; cli configs
user-agent = "npm/3.10.9 node/v6.9.2 darwin x64"

; userconfig /Users/jere/.npmrc
chromedriver_cdnurl = "http://npm.taobao.org/mirrors/chromedriver"
operadriver_cdnurl = "http://npm.taobao.org/mirrors/operadriver"
phantomjs_cdnurl = "https://npm.taobao.org/mirrors/phantomjs"
registry = "http://npm.int.jumei.com/"
sass_binary_site = "https://npm.taobao.org/mirrors/node-sass"

; globalconfig /Users/jere/.nvm/versions/node/v6.9.2/etc/npmrc
chromedriver_cdnurl = "http://npm.taobao.org/mirrors/chromedriver"
disturl = "http://npm.taobao.org/dist"
electron_mirror = "http://npm.taobao.org/mirrors/electron/"
git4win_mirror = "http://npm.taobao.org/mirrors/git-for-windows"
iojs_org_mirror = "http://npm.taobao.org/mirrors/iojs"
nodejs_org_mirror = "http://npm.taobao.org/mirrors/node"
nodist_iojs_mirror = "http://npm.taobao.org/mirrors/iojs"
nodist_node_mirror = "http://npm.taobao.org/mirrors/node"
nvm_iojs_org_mirror = "http://npm.taobao.org/mirrors/iojs"
nvm_nodejs_org_mirror = "http://npm.taobao.org/mirrors/node"
nvmw_iojs_org_mirror = "http://npm.taobao.org/mirrors/iojs"
nvmw_nodejs_org_mirror = "http://npm.taobao.org/mirrors/node"
nvmw_npm_mirror = "http://npm.taobao.org/mirrors/npm"
operadriver_cdnurl = "http://npm.taobao.org/mirrors/operadriver"
python_mirror = "http://npm.taobao.org/mirrors/python"
sqlite3_binary_site = "http://npm.taobao.org/mirrors/sqlite3"

; node bin location = /Users/jere/.nvm/versions/node/v6.9.2/bin/node
; cwd = /Users/jere/jm/shequ
; HOME = /Users/jere
; "npm config ls -l" to show all defaults.`



mine mac is working  well with mine private config.

**Comment by gucong3000** [comment]
fixed in #11
