### ISSUE TITLE
Host

### ISSUE THREAD

**Issue by leandroaps** [gucong3000/mirror-config-china#58]
I'm using Jenkins to create a pipeline with the Puppetter, but the host from China is blocked on my network (Brazil), there's a way to download Chromium from another host?

**Comment by gucong3000** [comment]
Here is some docs for this issue:
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#environment-variables

**Comment by leandroaps** [comment]
I try everything, but this is blocked on my network, I don't know if it's because this is hosted on China or other-thing. I'll try some offline options like downloading the package for Chromium and build a Dockerfile for it.

**Comment by gucong3000** [comment]
Try this:
```bash
npm i puppeteer -- puppeteer-download-host=https://storage.googleapis.com
```
If you can access Google through a proxy
```
npm i puppeteer --puppeteer-download-host=https://storage.googleapis.com --https-proxy=http://your.proxy.host

```
