### ISSUE TITLE
兄弟,你是不干开发了吗?

### ISSUE THREAD

**Issue by happy-func** [gucong3000/mirror-config-china#83]
项目是不是转出去,保持正常迭代维护?

**Comment by jiankafei** [comment]
> 项目是不是转出去,保持正常迭代维护?
要不你给接了？

**Comment by jiankafei** [comment]
> 项目是不是转出去,保持正常迭代维护?

要不你给接了。

**Comment by happy-func** [comment]
> > 项目是不是转出去,保持正常迭代维护?
> 
> 要不你给接了。

我这node一知半解，接过来只能仰仗列为大佬PR了

**Comment by happy-func** [comment]
use nrm
